server:
  port: 8081

spring:
  application:
    name: hotel-service

  datasource:
    url: jdbc:h2:mem:hoteldb;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.web.access: DEBUG
    org.springframework.security.web.authentication: DEBUG
    org.springframework.security.web.FilterChainProxy: TRACE
